### ISSUE TITLE
Lightbulbs become unresponsive, cause HomeBridge to stop working

### ISSUE THREAD

**Issue by Tiger519** [leematt/homebridge-tplink-lightbulb#2]
I'm having issues with the tplink-lightbulb plugin causing HomeBridge to stop working. I'm using it with the LB110 lightbulbs. It autodetects and connects fine, and for a time it reports status and controls the lightbulbs appropriately. But after a time, the lightbulbs stop responding. They don't show "no response" in the Home app, but they will either fail to respond to commands, or they will appear to respond (I'll see the command in terminal and even Siri will report the state change), but not actually change state.

The larger issue seems to be that this unresponsiveness seems to affect other integrations as well. I was using in conjunction with the Kevo plugin, and the whole system would become unresponsive. The only way to get it working again was to restart homebridge. I tried all the tricks (change HomeBridge name/pin, remove and re-pair HomeBridge, uninstall/reinstall plugins, rebuild homebridge, firewall settings, etc) and nothing seemed to address to issue. I had it working for a while running HomeBridge as a service and setting a task to restart the service at 10 minute intervals, but for some reason I couldn't get HomeBridge to show up as a hub after a while.

I had done some testing with removing the Kevo plugin, as the lightbulbs seemed to be working fine before then, but then I realized I was experiencing the same issue after some time with just that running. So i tried Kevo only and then everything became stable. So I think there definitely is some issue with the plugin when used with the LB110 model.

I'm on Windows 10 and I could not figure out how to get any logs. I tried running in DEBUG mode from GIT-Bash, but it wasn't really giving me any additional information. I've given up for now and am just using Kevo with HomeBridge, but I'd love to get this working with the lightbulbs. I'm happy to provide additional information to help troubleshoot this if someone can give me some direction on how to get it.

**Comment by leematt** [comment]
Thanks for bringing this up. I've started having some issues with unresponsiveness as well, and thought it might just be an issue with my bulb since the plugin had been working before. I didn't realize anyone was using this plugin yet, honestly, or I would've started debugging sooner. I have not noticed the unresponsiveness affecting Homebridge itself as much as you have, but it could be the same issue I've had with my LB120. I will start digging into it.

**Comment by leematt** [comment]
I've found that the [tplink-lightbulb](https://github.com/konsumer/tplink-lightbulb) interface occasionally does not receive a response from the bulb, which causes this plugin to hang and wait. I've just published a patch that adds a timeout to the request and retries on timeout. Can you update and see if that resolves the unresponsiveness? I haven't noticed unresponsiveness from other requests, but it's possible there are more that need to be addressed.

**Comment by leematt** [comment]
I've found another issue, maybe related to discovery or registration of bulbs. I'm going to keep working on this, but in the meantime, if you are having trouble with version `1.0.4` try deleting your `cachedAccessories` Homebridge cache, or at least removing the objects for `TplinkLightbulb` accessories, and you might be able to get it working.
