### ISSUE TITLE
Platform initializes then nothing.

### ISSUE THREAD

**Issue by UNiXMIT** [leematt/homebridge-tplink-lightbulb#5]
I've installed the plugin and started homebridge. The platform initializes then nothing. No errors and the bulb doesn't show up. Do I need to do anything else? Thanks.

**Comment by UNiXMIT** [comment]
UPDATE - I started homebridge again last night and left it. Immediately the platform initialized and then nothing. I checked the status of homebridge just now and I see 'Configuring: DiningRoom' at 8am. Should it take that long? Anyway it's working now so that's good.

**Comment by leematt** [comment]
Hi @UNiXMIT! It shouldn't take that long at all. I've not experienced this problem, and am not sure how to recreate it. Let me know if it's happened again. I'm guessing it could be a deeper issue with bulb discovery, somewhere along the chain. Most of that happens outside this package, so I'm going to close the issue for now.
