### ISSUE TITLE
TypeError: this is not a typed array.

### ISSUE THREAD

**Issue by datnguyen0606** [leematt/homebridge-tplink-lightbulb#6]
Hi there, I got the issue when starting homebridge 

Homebridge is running on port 51826.
/usr/local/lib/node_modules/homebridge-tplink-lightbulb/node_modules/tplink-lightbulb/build/lib.js:303
        var msgBuf = Bulb.encrypt(Buffer.from('{"system":{"get_sysinfo":{}}}'));
                                         ^
TypeError: this is not a typed array.
    at Function.from (native)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-tplink-lightbulb/node_modules/tplink-lightbulb/build/lib.js:303:42)
    at Socket.g (events.js:260:16)

My current installed version on macOs 10.12
homebridge@0.4.22
homebridge-tplink-lightbulb@1.0.6

**Comment by leematt** [comment]
Hi @datnguyen0606! The error appears to be originating from the tplink-lightbulb package (a dependency of this package). Which version of Node.js are you running (`node -v`)? It appears that Buffer.from() was introduced in Node.js 6.0, so if your version is older that could be the problem.
