### ISSUE TITLE
Lightbulbs added even without entry in config.json

### ISSUE THREAD

**Issue by Tiger519** [leematt/homebridge-tplink-lightbulb#9]
If I have the plugin installed, the bulbs are auto-recognized and added even if I'm running in a separate instance of Homebridge (but same application, I'm running it with -U flag to isolate accessories so if they crash and I have to remove the bridge, I don't have to setup everything all over again, e.g. I'm running `/opt/node/bin/homebridge -U ~/.tplinkbridge` to try to isolate my TP Link bulbs. This isn't an issue as much as I think it's something to do with the way Homebridge handles platforms. Because of the way I'm running these separate instances, I can't use the plugin else I'd end up with the bulbs added in every bridge I am running (currently 3).

Is there something in the code which is causing these bulbs to auto-recognize even if the platform isn't specified in the JSON, and if so is it possible to remove that function without breaking the plugin?

**Comment by leematt** [comment]
The [`scan` function in `index.js`](https://github.com/leematt/homebridge-tplink-lightbulb/blob/a54ea4d86be7da0707446c418369ff36f788d30f/index.js#L31) handles the automated recognition and registration of the bulbs. It could be modified to only recognize previously registered bulbs by removing [the line that initializes the new bulbs](https://github.com/leematt/homebridge-tplink-lightbulb/blob/a54ea4d86be7da0707446c418369ff36f788d30f/index.js#L39).

I recommend taking a look at the [homebridge-tplink-smarthome](https://github.com/plasticrake/homebridge-tplink-smarthome) plugin, which now has support for the TP-Link smart bulbs. It is more reliable than the current version of this plugin. It also auto-recognizes devices, however, and may require a similar tweak.
